### ISSUE TITLE
Crash trying to run application after installing JsoupFeature

### ISSUE THREAD

**Issue by Jorkoh** [T-Fowl/ktor-jsoup#6]
Hey! thanks for building this feature, it's just what I need on my project. Unfortunately when I try to run the application it crashes on startup. I tried with an empty project (just an HttpClient with just this feature installed) but the problem persists.

Here is the trace:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:166)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:384)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:330)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:274)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:290)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:272)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:125)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
	at com.asdfasdf.ApplicationKt.main(Application.kt:7)
Caused by: java.lang.NoSuchMethodError: io.ktor.client.HttpClient.getResponsePipeline()Lio/ktor/client/response/HttpResponsePipeline;
	at com.tfowl.ktor.client.features.JsoupFeature$Feature.install(JsoupFeature.kt:57)
	at com.tfowl.ktor.client.features.JsoupFeature$Feature.install(JsoupFeature.kt:50)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:72)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:16)
	at io.ktor.client.HttpClientConfig.install(HttpClientConfig.kt:90)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:146)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
	at io.ktor.client.HttpClientJvmKt.HttpClient(HttpClientJvm.kt:21)
	at com.asdfasdf.ApplicationKt.module(Application.kt:11)
	at com.asdfasdf.ApplicationKt.module$default(Application.kt:10)
	... 24 more

Process finished with exit code 1
```
I'm using version 1.1.0 and Ktor 1.3.2 It seems to work on Ktor 1.2.5 but breaks on +1.3.0, if you need any more info just tell me.

**Comment by T-Fowl** [comment]
Glad to hear it's been useful! 1.2.0 should fix this issue but let me know if I missed something 😄
